### ISSUE TITLE
师傅，BehindShell连接方式http://xxxx/poi,密码rebeyond。我测试连接不上。

### ISSUE THREAD

**Issue by wpf97** [ethushiroha/JavaAgentTools#1]

**Comment by ethushiroha** [comment]
请问您使用的过程中有无报错信息/提示信息
还有冰蝎的版本是否为beta10之后？（冰蝎在 beta 10 之后摆脱对 pageContext 的依赖）

**Comment by wpf97** [comment]
注入cmd马正常，注入冰蝎之后访问全是空白，用冰蝎3.0 beta6连接不上。无法获取密钥。测试是用的actuator-testbed-0.1.0.jar测试的。

**Comment by ethushiroha** [comment]
注意：冰蝎内存马仅适用于 **冰蝎 3.0 beta10** 之后的版本
原因：在冰蝎 3.0 beta 10 之前，依赖于 tomcat 特有的 pageContext 对象，而在 beta10 及之后，使用了反射，可以使用 hashmap进行调用
在之前的回复中已经提到了 **冰蝎版本的问题**。

**Comment by wpf97** [comment]
忘记说了，注入之后冰蝎3.0 beta10之后的版本是可以正常连接。但是访问web任意页面（包括正常页面）/env等等都是空白。这种情况有方法解决吗？

**Comment by ethushiroha** [comment]
看代码中的 resources/start.txt 文件你就知道为什么 /env 路由是空的了
我只劫持了 /poi 路由，如果想要别的路由可以使用以下两种方法：
1. 更改 start.txt 中的 if 判断
2. 删除 if

**Comment by wpf97** [comment]
好的，谢谢了

**Comment by ethushiroha** [comment]
> 忘记说了，注入之后冰蝎3.0 beta10之后的版本是可以正常连接。但是访问web任意页面（包括正常页面）/env等等都是空白。这种情况有方法解决吗？

时隔一年之后的回复，不好意思，因为之前这个项目也没拿来实际用，就没这么上心，前几天有师傅反应了同样的问题，原因是在 start.txt 中，return 语句到了 if 语句的外面，导致所有的请求全部 return 了，这才导致所有的页面均为空白，目前已修复，还望师傅勿怪
