### ISSUE TITLE
内存马注入后路径是什么

### ISSUE THREAD

**Issue by mrknow001** [ethushiroha/JavaAgentTools#3]
内存马注入后路径是什么

**Comment by ethushiroha** [comment]
这个算是 filter 类型的内存马，所以对任意的路由都起作用。
如果发现某个路由没起作用，可能性有：

1. 浏览器缓存
2. 这个路由的优先级在filter之上（不太可能）
3. 这个路由不经过filter
4. 本内存马不适用于这个jar，建议把jar拿下来看一下代码
