### ISSUE TITLE
师傅你好，win10下 使用release 下的agent.jar 和 spring.jar报错

### ISSUE THREAD

**Issue by yshdxm** [ethushiroha/JavaAgentTools#4]
![image](https://user-images.githubusercontent.com/54091599/185294743-69633bd9-d232-4902-b121-9b8a5ad95844.png)
请问这是什么原因造成的

**Comment by yshdxm** [comment]
在控制台看到报错信息
显示：opening zip file or JAR manifest missing:

**Comment by ethushiroha** [comment]
请问师傅：springMemshell.jar 是否在进程 4568 的活动目录下（例如，在/tmp 目录下 以`java -jar 1.jar`的形式启动了进程 4568，那么springMemshell.jar 也需要放在 /tmp 目录下）。如果不是，请移动之后重试。

**Comment by yshdxm** [comment]
可以了  cmd马是没问题的 谢谢师傅 ，但是我这边冰鞋马显示注入成功 但是访问还是什么都没有

**Comment by yshdxm** [comment]
我这把同时注入了cmd和冰鞋 发现 cmd可以 冰鞋没效果，是不是先注入哪个哪个就有优先级

**Comment by yshdxm** [comment]
对了 师傅我这把注入了cmd马之后，发现使用model=exit 之后 还是可以执行命令 并不能够退出内存马

**Comment by ethushiroha** [comment]
第一个问题：
冰蝎内存马注入的路径是 `/poi`，连接密码为 rebeyond，支持的版本为 冰蝎3beta 10 及以后（冰蝎4暂未尝试，不确定适配情况）
请师傅：
1. 检查使用的冰蝎版本
2. 检查连接的路径、密码

第二个问题：
我还没有试过一起注入的情况，我会在尝试，并且debug之后给师傅回复

第三个问题：
师傅在model=exit的时候完整的请求包可以可以提供一下吗？我本地测试的没有问题。

**Comment by ethushiroha** [comment]
第二个问题：
经过调试，由于我在 Behinder.jar 和 springMemShell.jar 中，修改源码的文件名都是 start.txt；所以在注入过程中，后注入的agent也会找到先注入的 agent 中的 start.txt 因此会导致后注入agent注入失败。
当二者资源名不同时，后注入的agent会覆盖先注入的agent（因为二者hook的是同一个类）

**Comment by yshdxm** [comment]
好的 谢谢师傅，针对第二问题，我是不是可以这么理解，我先注入的springmemshell, 如果想注入Behinder的话 修改下Behinder中的start.txt文件名，改成不同的就行，是不是就可以覆盖掉springmemshell

**Comment by yshdxm** [comment]
多谢师父，我本地测试已经可以覆盖掉 cmd内存马，问题已解决
