### ISSUE TITLE
师傅，你好，Neo-reGeorg一直提示[CRITICAL]  Bad KEY or non-neoreg server

### ISSUE THREAD

**Issue by wpf97** [ethushiroha/JavaAgentTools#5]
师傅，你好，Neo-reGeorg一直提示[CRITICAL]  Bad KEY or non-neoreg server
neo-regeorg 2.6
python3 neoreg.py --url "http:///?password=stdout&model=proxy" -k "stdout" -p 9999 --skip

**Comment by ethushiroha** [comment]
不好意思，现在才看到你的 issue，是这样，**neo-reGeorg 的路由地址为：/eGluZ3hpbmcK**（写在`com.stdout.Utils.PreDelURI` 内） ，即：http://xxx.yyy/eGluZ3hpbmcK，不需要带上 ?password=xxx&model=yyy
